version: '3.8'

services:
  patient-service-db:
    image: postgres:latest
    container_name: patient-service-db
    ports:
      - "5000:5432"
    volumes:
      - C:/Users/CRISTIAN/db_volumes/patient-service-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - internal

networks:
  internal:
    driver: bridge
